#Database PostgreSQL

development:
  database: curve_yc_dev
  adapter: postgresql
  host: localhost

test:
  database: curve_yc_test
  adapter: postgresql
  host: localhost

stage:
  adapter: postgresql
  database: curve_yc_stage
  pool: 5
  timeout: 5000

production:
  database: curve_yc_production
  adapter:  postgresql
  host:     159.65.44.196
  username: "deploy"
  password: "curv3y0urcar33r"
  pool:     20
  timeout:  30000
